auto/auto/urls.py
from django.contrib import admin
from django.urls import path, include
from autocrud import views

urlpatterns = [
    path('', views.home, name='home'),
    path('crud/', include('autocrud.urls')),
    path('admin/', admin.site.urls),
]

auto/autocrud/urls.py
from django.urls import path
from . import views

app_name = 'autocrud' #Nas templates deve colocar o app_name nos links {% url 'app_name:name'%} -> autocrud:autos
urlpatterns = [
    path('login/', views.login, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),

    path('autos/', views.autos, name='autos'),
    path('auto/create/', views.auto_create, name='auto_create'),
    path('auto/<int:autoid>/update/', views.auto_update, name='auto_update'),
    path('auto/<int:autoid>/delete/', views.auto_delete, name='auto_delete'),

    path('makes/', views.makes, name='makes'),
    path('make/create/', views.make_create, name='make_create'),
    path('make/<int:makeid>/update/', views.make_update, name='make_update'),
    path('make/<int:makeid>/delete/', views.make_delete, name='make_delete'),
]

auto/autocrud/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User

# Create your models here.
class Make(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.name

class Auto(models.Model):
    nickname = models.CharField(max_length=200)
    mileage = models.PositiveIntegerField()
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    user_specific_id = models.PositiveIntegerField()

    def __str__(self):
        return self.nickname
    
    def save(self, *args, **kwargs):
        if not self.id:  # Se o registro ainda não foi salvo
            # Encontra o maior ID específico do usuário atual e adiciona 1
            max_id = Auto.objects.filter(user=self.user).aggregate(models.Max('user_specific_id'))['user_specific_id__max']
            self.user_specific_id = 1 if max_id is None else max_id + 1
        super().save(*args, **kwargs)

auto/autocrud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from autocrud.models import Auto, Make

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        nome = request.user.username
        return render(request, 'home.html', {'logado': True, 'user': nome})
    else:
        return render(request, 'home.html')
    
def cadastro(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = User.objects.filter(username=username).first()

        if user:
            return HttpResponse('Já existe um usuário com esse username')
        
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save
        cadastrado = True
        return redirect('home')
    else:
        return render(request, 'cadastro.html')

def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login_django(request, user)
            return redirect('autocrud:autos')
        else:
            return HttpResponse('Usuário ou senha inválidos')

@login_required(login_url='/crud/login/') #Faz a autenticação e a gente escolhe a página de login (Por padrão é '/accounts/login/')
def autos(request):
    # if request.user.is_authenticated:
    if request.method == 'POST' and 'sair' in request.POST:
        logout(request)
        return redirect('autocrud:autos')
    else:
        user_id = request.user.id
        makeCount = Make.objects.filter(user_id=user_id).count()
        makes = Make.objects.filter(user_id=user_id)
        autos = Auto.objects.filter(user_id=user_id)
        return render(request, 'autolist.html', {'makeCount': makeCount, 'makes': makes, 'autos': autos, 'previous_url': request.META.get('HTTP_REFERER', None)})
    # else:
    #   return redirect('login')

@login_required(login_url='/crud/login/')
def makes(request):
    if request.method == 'POST' and 'sair' in request.POST:
        logout(request)
        return redirect('autocrud:autos')
    else:
        user_id = request.user.id
        makes = Make.objects.filter(user_id=user_id)
        autoCount = Auto.objects.filter(user_id=user_id).count()
        return render(request, 'makelist.html', {'makes': makes, 'autoCount': autoCount, 'previous_url': request.META.get('HTTP_REFERER', None)})

@login_required(login_url='/crud/login/')
def auto_create(request):
    if request.method == 'GET':
        return redirect('autocrud:autos')
    else:
        nickname = request.POST.get('name')
        mileage = request.POST.get('mileage')
        make_id = request.POST.get('make')
        user_id = request.user.id
        auto = Auto(nickname=nickname, mileage=mileage, user_id=user_id, make_id=make_id)
        auto.save()
    return redirect('autocrud:autos')

@login_required(login_url='/crud/login/')
def auto_update(request, autoid):
    if request.method == 'GET':
        try:
            auto = Auto.objects.get(id=autoid)
        except:
            return HttpResponse("Esse carro não existe")
        user_id = request.user.id
        if verifica(auto.user_id, user_id):
            user_id = request.user.id
            makeCount = Make.objects.filter(user_id=user_id).count()
            makes = Make.objects.filter(user_id=user_id)
            autos = Auto.objects.filter(user_id=user_id)
            return render(request, 'updateauto.html', {'makeCount': makeCount, 'makes': makes, 'autos': autos, 'autoId': autoid, 'auto': auto})
        else:
            return HttpResponse('Você não pode editar esse carro')
    else:
        auto = Auto.objects.get(id=autoid)
        auto.nickname = request.POST.get('name')
        auto.mileage = request.POST.get('mileage')
        auto.make_id = request.POST.get('make')
        auto.save()
        return redirect('autocrud:autos')

@login_required(login_url='/crud/login/')
def auto_delete(request, autoid): 
    try:
        auto = Auto.objects.get(id=autoid)
    except:
        return HttpResponse("Esse carro não existe")
    if verifica(auto.user_id, request.user.id):
        auto.delete()
    else:
        return HttpResponse('Você não pode deletar esse carro')
    return redirect('autocrud:autos')

@login_required(login_url='/crud/login/')
def make_create(request):
    if request.method == 'GET':
        return redirect('autocrud:makes')
    else:
        nome = request.POST.get('name')
        user_id = request.user.id
        if len(nome) > 2:
            make = Make(name=nome, user_id=user_id)
            make.save()
        else:
            return HttpResponse('Your make must be greater than 2 characters')
    if 'auto' in request.POST:
        return redirect('autocrud:autos')
    else:
        return redirect('autocrud:makes')

@login_required(login_url='/crud/login/')
def make_update(request, makeid):
    if request.method == 'GET':
        try:
            make = Make.objects.get(id=makeid)
            if verifica(make.user_id, request.user.id):
                makes = Make.objects.filter(user_id=request.user.id)
                autoCount = Auto.objects.filter(user_id=request.user.id).count()
                return render(request, 'updatemake.html', {'make': make, 'makes': makes, 'autoCount': autoCount })
            else:
                return HttpResponse("Você não pode editar essa marca")
        except:
            return HttpResponse("Essa marca não existe")
    else:
        make = get_object_or_404(Make, id=makeid)
        newName = request.POST.get('name')
        make.name = newName
        make.save()
        return redirect('autocrud:makes')

@login_required(login_url='/crud/login/')
def make_delete(request, makeid):
    try:
        make = Make.objects.get(id=makeid)
    except:
        return HttpResponse("Essa marca não existe")
    if verifica(make.user_id, request.user.id):
        make.delete()
        return redirect('autocrud:makes')
    else:
        return HttpResponse("Você não pode deletar essa marca")

def verifica(objUserId, userId):
    if objUserId == userId:
        return True
    else:
        return False

auto/autocrud/templates/autolist.html
{% extends "base.html" %}

{% block content %}

    {% if not autos %}
    <div style="margin-top: 20px; background-color: white; padding: 10px 20px; border-radius: 5px; display: inline-block; overflow-y: auto;">
        <h1 style="font-size: 50px; color: #007bff;">Autos</h1>
        <p style="margin-top: 10px;">There are no autos in the library.</p>
        <p style="margin-top: 10px;">
            {% if makeCount > 0 %}
            <div style="text-align: right;">
                <button class="plus" id="openModalBtnAuto" style="border-radius: 5px; margin-top: 10px; padding-top: 5px; right: 0px;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
                </svg></button>
            </div>
            {% else %}
                Please add a make before you add an auto.
            {% endif %}
        </p>
    </div>
    {% endif %}

{% if autos %}
        <div style="margin-top: 20px; background-color: white; padding: 10px 20px; border-radius: 5px; display: inline-block;">
        <h1 style="font-size: 50px; margin: 0px 0px 20px 0px; color: #007bff;">Autos</h1>
            <ul style="list-style-type: none; padding: 0; text-align: center;">
                {% for auto in autos %}
                    <li style="margin-bottom: 10px; display: flex; align-items: center;">
                        {{ forloop.counter }}. {{ auto.nickname }} - {{ auto.make }} ({{ auto.mileage }} miles)
                        <a href="{% url 'autocrud:auto_update' auto.id %}">
                            <button id="openModalBtnAutoUpdate" class="edit" style="background-color: transparent; border: none; cursor: pointer; margin-right: -6px;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                            </svg></button>
                        </a>
                        <form action="{% url 'autocrud:auto_delete' auto.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="delete" style="border: none; background-color: transparent; display: block;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                            </svg></button>
                        </form>
                    </li>
                    {% comment %} <div id="myModalAutoUpdate" class="modalAutoUpdate">
                        <div class="modal-contentAutoUpdate">
                            <div style="text-align: center;">
                                <h2 style="margin-bottom: 20px">Adding an auto</h2>
                                <form action="{% url 'autocrud:auto_update' auto.id %}" method="POST" style="display: inline-block; text-align: left;">
                                    {% csrf_token %}
                                    <label for="name" style="display: inline-block;">Nickname:</label>
                                    <input type="text" name="name" value="{{auto.nickname}}" required style="display: inline-block; margin-bottom: 10px;">
                                    <br>
                                    <label for="mileage" style="display: inline-block;">Mileage:</label>
                                    <input type="number" min="0" onkeydown="return event.keyCode !== 69" name="mileage" value="{{auto.mileage}}" required style="display: inline-block; margin-bottom: 10px">
                                    <br>
                                    <label for="make" style="display: inline-block;">Make:</label>
                                    <select name="make" style="display: inline-block;" required>
                                        <option value="{{ auto.make_id }}" selected>{{ auto.make.name }}</option>
                                        {% for make in makes %}
                                            {% if make.id != auto.make_id %}
                                                <option value="{{ make.id }}">{{ make.name }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                    <br>
                                    <div style="padding: 10px; text-align: center;">
                                        <input type="submit" value="Editar" class="input">
                                        <input type="button" value="Cancelar" class="closeAutoUpdate">
                                        <input type="hidden" name="auto">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> {% endcomment %}
                {% endfor %} 
            </ul>
                {% if makeCount > 0 %}
                    <div style="text-align: right;">
                        <button class="plus" id="openModalBtnAuto" style="border-radius: 5px; margin-top: 10px; padding-top: 5px; right: 0px;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
                        </svg></button>
                    </div>
                {% else %}
                    <p style="margin-top: 10px;">Please add a make before you add an auto.</p>
                {% endif %}
        </div>
{% endif %}
        
        <p style="margin-top: 30px; margin-bottom: 25px;">
            <a href="{% url 'autocrud:makes' %}" class="viewmakes">View makes ( {{ makeCount }} )</a>
            <button class="plus" id="openModalBtn" style="padding: 10px; margin-left: 26px;">Add a make</button>
        </p>
    
        <div id="myModal" class="modal">
            <div class="modal-content">
                <h2 style="margin-bottom: 20px">Adding a make</h2>
                <form action="{% url 'autocrud:make_create' %}" method="POST">
                    {% csrf_token %}
                    <label for="name">Nome:</label>
                    <input type="text" name="name" placeholder="Ex: Volkswagen" required>
                    <div style="padding: 10px;">
                        <input type="submit" value="Criar" class="input">
                        <input type="button" value="Cancelar" class="close">
                        <input type="hidden" name="auto">
                    </div>
                </form>
            </div>
        </div>

    <div id="myModalAuto" class="modalAuto">
        <div class="modal-contentAuto">
            <div style="text-align: center;">
                <h2 style="margin-bottom: 20px">Adding an auto</h2>
                <form action="{% url 'autocrud:auto_create' %}" method="POST" style="display: inline-block; text-align: left;">
                    {% csrf_token %}
                    <label for="name" style="display: inline-block;">Nickname:</label>
                    <input type="text" name="name" placeholder="Camaro" required style="display: inline-block; margin-bottom: 10px;">
                    <br>
                    <label for="mileage" style="display: inline-block;">Mileage:</label>
                    <input type="number" min="0" onkeydown="return event.keyCode !== 69" name="mileage" placeholder="Ex: 20000" required style="display: inline-block; margin-bottom: 10px">
                    <br>
                    <label for="make" style="display: inline-block;">Make:</label>
                    <select name="make" style="display: inline-block;" required>
                        {% for make in makes %}
                            <option value="{{ make.id }}">{{ make.name }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <div style="padding: 10px; text-align: center;">
                        <input type="submit" value="Criar" class="input">
                        <input type="button" value="Cancelar" class="closeAuto">
                        <input type="hidden" name="auto">
                    </div>
                </form>
            </div>
            
        </div>
    </div>

    {% block AutoUpdate %}
    {% endblock AutoUpdate %}

{% endblock content %}

auto/autocrud/templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auto CRUD - Cadastro</title>
    <style>
        body {
            text-align: center;
            background-image: linear-gradient(to bottom, white, lightgrey);
            background-size: 100vw 100vh;
            background-repeat: no-repeat;
            font-family: 'Arial', sans-serif;
            margin: 0; /* Remove margens padrão */
            padding: 0; /* Remove preenchimento padrão */
        }
        
        h1 {
            color: #333; /* Cor do texto do título */
        }
        
        label {
            color: #555; /* Cor do texto das etiquetas */
            display: inline-block; /* Torna as etiquetas em linha com os campos de entrada */
            width: 120px; /* Define uma largura fixa para as etiquetas (ajuste conforme necessário) */
            text-align: center; /* Alinha o texto das etiquetas à direita */
        }
        
        .form {
            margin-top: 25vh; 
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            padding: 10px; /* Adiciona preenchimento aos campos de entrada */
            margin: 5px; /* Adiciona margem aos campos de entrada */
            border-radius: 5px; /* Adiciona borda arredondada aos campos de entrada */
            border: 1px solid #ccc; /* Adiciona uma borda sólida com cor cinza aos campos de entrada */
        }
        
        input[type="submit"] {
            padding: 10px 20px; /* Adiciona preenchimento aos botões */
            margin-top: 10px; /* Adiciona margem superior ao botão */
            border: none; /* Remove a borda do botão */
            background-color: #007bff; /* Cor de fundo do botão */
            color: white; /* Cor do texto do botão */
            border-radius: 5px; /* Adiciona borda arredondada ao botão */
            cursor: pointer; /* Muda o cursor para o formato de mão ao passar por cima do botão */
        }
        
        input[type="submit"]:hover {
            background-color: #0056b3; /* Altera a cor de fundo ao passar o mouse sobre o botão */
        }
        
        #mensagem {
            color: green; /* Cor do texto da mensagem de sucesso */
        }

        .button a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #ADD8E6;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .button a:hover {
            background-color: #ADD8F9;
        }
        
        footer {
            font-size: 12px;
            font-family: 'arial';
            width: 100%;
            height: 100px;
            position: fixed;
            bottom: 0;
            left: 0;
            margin-bottom: -50px;
        }
    </style>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'autocrud/images/caricon.ico' %}" type="image/x-icon">
</head>
<body>
    <div class="form">
        <h1>Cadastro</h1>
        <form action="{% url 'autocrud:cadastro' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" placeholder="Username" name="username" required>
            <br><br>
            <label for="email">E-mail:</label>
            <input type="email" placeholder="E-mail" name="email" required>
            <br><br>
            <label for="password">Password:</label>
            <input type="password" placeholder="Password" name="password" required>
            <br><br>
            <input type="submit" value="Cadastrar" style="font-weight: bold;">
            <br><br>
        </form>
    </div>
    {% if cadastrado %}
        <p style="color: green;" id="mensagem">Cadastrado com sucesso!</p>
    {% endif %}
    <div class="button">
        <a href="{% url 'home' %}">Voltar para a página inicial</a>
    </div>
    <footer>
        <p>© 2024 Auto CRUD</p>
    </footer>
</body>
<script>
    // Função para esconder a mensagem após um certo tempo
    function esconderMensagem() {
        document.getElementById("mensagem").style.display = "none";
    }

    // Esconde a mensagem após 2 segundos (2000 milissegundos)
    setTimeout(esconderMensagem, 2000);
</script>
</html>

auto/autocrud/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auto CRUD - Home</title>
    {% load static %}
    <style>

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            text-align: center;
            background-image: url({% static 'autocrud/images/background.jpg' %});
            background-size: 100vw 100vh;
            background-repeat: no-repeat;
        }

        .b{
            font-family: 'arial';
            font-size: 20px;
            text-decoration: none;
            margin-right: 20px;
            color: white;
            background-color: #007bff;
            border-radius: 10px;
            padding: 15px 10px;
            margin: auto;
        }

        .b:hover {
            background-color: #0056b3;
            box-shadow: 0px 0px 2px black
        }

        img {
            
            
            max-width: 90%;
            width: 390px;
        }

        .logged-in-message {
            padding: 10px;
            margin-top: 20px;
            font-family: 'arial';
            width: auto;
            margin: auto;
        }

        .logged-in-message h2 {
            color: #333;
            font-size: 20px;
            margin-bottom: 10px;
        }

        .logged-in-message a {
            color: #007bff; /* Cor do link */
            text-decoration: none;
            font-weight: bold;
        }

        .logged-in-message a:hover {
            text-decoration: underline; /* Efeito ao passar o mouse */
        }

        footer {
            font-size: 12px;
            color: white;
            font-family: 'arial';
            height: 100px;
            width: 100%;
            position: absolute;
            bottom: 0;
        }

    </style>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'autocrud/images/caricon.ico' %}" type="image/x-icon">
</head>
<body>
    <div style="background-image: linear-gradient(#ffffff30, #d3d3d330); height: 100vh; position: relative; ">
        <div style="background-color: white; border-radius: 5px; padding: 10px; display: inline-block; margin-top: 10vh; box-shadow: 1px 1px 10px black">
            <img src="{% static 'autocrud/images/autologo.png' %}">
            {% if not logado %}
            <div class="links" style="display: flex; flex-direction: column;">
                <a href="{% url 'autocrud:cadastro' %}" class="b" style="margin-bottom: 20px; ">Cadastrar-se</a>
                <p class="logged-in-message">Você já tem login? <a href="{% url 'autocrud:login' %}">Clique aqui para entrar</a></p>
            </div>
            {% else %}
            <div class="logged-in-message">
                <h2>Você já está logado(a) {{ user }}! <a href="{% url 'autocrud:autos' %}"> Clique aqui para entrar</a></h2>
            </div>
            {% endif %}
        </div>
        <footer>
            <p style="margin-top: 70px;">© 2024 Auto CRUD</p>
        </footer>
    </div>
</body>
</html>

auto/autocrud/templates/makelist.html
{% extends "base.html" %}

{% block content %}

{% if makes %}
<div style="margin-top: 20px; background-color: white; padding: 10px 20px; border-radius: 5px; display: inline-block; width: 230px;">
    <h1 style="font-size: 50px; margin: 0px 0px 20px 0px; color: #007bff;">Makes</h1>
    <ul style="list-style-type: none; padding: 0; text-align: center;">
        {% for make in makes %} 
                <li style="margin-bottom: 10px; display: flex; align-items: center; justify-content: space-between;">
                    {{ forloop.counter }}. {{ make.name }}
                    <div style="display: flex; align-items: center; ">
                        <a href="{% url 'autocrud:make_update' make.id %}" class="edit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                            </svg>
                        </a>
                        <form action="{% url 'autocrud:make_delete' make.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="delete" style="border: none; background-color: transparent; display: block;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </button>
                        </form>
                    </div>
                </li>
                {% endfor %}
        </ul>
    </div>
{% else %}
<div style="margin-top: 20px; background-color: white; padding: 10px 20px; border-radius: 5px; display: inline-block;">
    <h1 style="font-size: 50px; color: #007bff;">Makes</h1>
    <p style="margin-top: 10px;">There are no makes in the library.</p>
    <p style="margin-top: 10px;">
    </p>
</div>
{% endif %}

<div id="myModal" class="modal">
<div class="modal-content">
    <h2 style="margin-bottom: 20px">Adding a make</h2>
    <form action="{% url 'autocrud:make_create' %}" method="POST">
        {% csrf_token %}
        <label for="name">Nome:</label>
        <input type="text" name="name" placeholder="Ex: Volkswagen" required>
        <div style="padding: 10px;">
            <input type="submit" value="Criar" class="input">
            <input type="button" value="Cancelar" class="close">
        </div>
    </form>
</div>
</div>
<p style="margin-top: 30px; margin-bottom: 25px;">
    <a href="{% url 'autocrud:autos' %}" class="viewmakes" style="margin-right: 3px;">View autos ( {{ autoCount }} )</a>
    <button class="plus" id="openModalBtn" style="padding: 10px; margin-left: 26px;">Add a make</button>
</p>

{% block MakeUpdate %}
{% endblock MakeUpdate %}

{% endblock %}